package com.sunbeat.sshclient.domain.ssh

import android.util.Log
import com.sunbeat.sshclient.data.local.SessionEntity
import com.termux.terminal.TerminalEmulator
import com.termux.terminal.TerminalOutput
import com.termux.terminal.TerminalSessionClient
import java.io.InputStream
import java.io.OutputStream
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

/**
 * A terminal session bound to an SSH connection.
 *
 * This is **not** the same as [com.termux.terminal.TerminalSession].  The
 * Termux class manages a local PTY subprocess via JNI, which is unsuitable
 * for an SSH client.  Instead we own a [TerminalEmulator] directly, giving us
 * the escape-sequence / screen-buffer engine without spawning a local process.
 *
 * Data flow:
 * - Remote output  → [feedRemoteData]  → [emulator.append] → screen buffer
 * - User input     → [write]            → [ptyOutputStream] → SSH channel
 * - Control responses generated by the emulator →
 *   [TerminalOutput.write] → [ptyOutputStream] → SSH channel
 *
 * @param dbSession      the Room entity describing this connection.
 * @param sshClient      the sshlib client handle (concrete type TBD at integration).
 * @param ptyInputStream input stream carrying remote→local data (SSH channel stdout).
 * @param ptyOutputStream output stream carrying local→remote data (SSH channel stdin).
 */
class TerminalSession(
    val dbSession: SessionEntity,
    internal val sshClient: Any,
    val ptyInputStream: InputStream,
    private val ptyOutputStream: OutputStream,
) {

    val id: Long get() = dbSession.id

    // Dedicated single-thread executor for SSH writes.
    // Keyboard events arrive on the main thread; ChannelOutputStream.write()
    // ultimately hits SocketOutputStream which is a network operation.
    private val writeExecutor: ExecutorService = Executors.newSingleThreadExecutor { r ->
        Thread(r, "SSH-stdin").apply { isDaemon = true }
    }

    // ── TerminalOutput bridge ─────────────────────────────────────────────
    // Must be declared BEFORE emulator since the emulator constructor
    // receives this as its TerminalOutput argument.

    private val termOutput = object : TerminalOutput() {
        override fun write(data: ByteArray, offset: Int, count: Int) {
            writeExecutor.execute {
                try {
                    ptyOutputStream.write(data, offset, count)
                    ptyOutputStream.flush()
                } catch (_: Exception) {
                    // SSH channel closed
                }
            }
        }

        override fun titleChanged(oldTitle: String?, newTitle: String?) = Unit
        override fun onCopyTextToClipboard(text: String?) = Unit
        override fun onPasteTextFromClipboard() = Unit
        override fun onBell() = Unit
        override fun onColorsChanged() = Unit
    }

    /** Terminal emulator that processes escape sequences and maintains the screen buffer.
     *  Constructor order: (TerminalOutput, columns, rows, transcriptRows, client) */
    val emulator: TerminalEmulator = TerminalEmulator(
        /* output       = */ termOutput,
        /* columns      = */ dbSession.cols,
        /* rows         = */ dbSession.rows,
        /* transcript   = */ SCROLLBACK_LINES,
        /* client       = */ NoopSessionClient,
    )

    /**
     * Called after every [feedRemoteData] so the UI can schedule a redraw.
     * The callback is invoked on the calling thread (typically IO); the
     * receiver must post to a main-thread Handler or equivalent.
     */
    var onEmulatorUpdated: (() -> Unit)? = null

    // ── Public API ────────────────────────────────────────────────────────

    /**
     * Feed a chunk of remote SSH output into the terminal emulator.
     * Must be serialised (call from a single coroutine/thread).
     */
    fun feedRemoteData(data: ByteArray) {
        emulator.append(data, data.size)
        onEmulatorUpdated?.invoke()
    }

    /** Write user input to the SSH channel (local → remote) from a background thread. */
    fun write(data: ByteArray) {
        writeExecutor.execute {
            try {
                ptyOutputStream.write(data)
                ptyOutputStream.flush()
            } catch (e: Exception) {
                Log.e("SSHTerm", "write failed: ${e.javaClass.simpleName}: ${e.message}")
            }
        }
    }

    fun write(text: String) {
        write(text.toByteArray())
    }

    /**
     * Resize the terminal emulator.
     *
     * Called when the [com.termux.view.TerminalView] dimensions change.
     * **Note** [TerminalEmulator.resize] accepts (cols, rows), not (rows, cols).
     */
    fun resize(rows: Int, cols: Int) {
        emulator.resize(cols, rows)
        // TODO: Notify SSH server of the new window dimensions via sshClient.
        //       e.g. sshClient.sendWindowChange(rows, cols)
    }

    /** Close SSH streams.  Idempotent. */
    fun close() {
        writeExecutor.shutdown()
        runCatching { ptyOutputStream.close() }
        runCatching { ptyInputStream.close() }
    }

    companion object {
        private const val SCROLLBACK_LINES = 32000

        /** Shared no-op [TerminalSessionClient] — no Termux session to report to. */
        private val NoopSessionClient = object : TerminalSessionClient {
            override fun onTextChanged(session: com.termux.terminal.TerminalSession?) = Unit
            override fun onTitleChanged(session: com.termux.terminal.TerminalSession?) = Unit
            override fun onSessionFinished(session: com.termux.terminal.TerminalSession?) = Unit
            override fun onCopyTextToClipboard(session: com.termux.terminal.TerminalSession?, text: String?) = Unit
            override fun onPasteTextFromClipboard(session: com.termux.terminal.TerminalSession?) = Unit
            override fun onBell(session: com.termux.terminal.TerminalSession?) = Unit
            override fun onColorsChanged(session: com.termux.terminal.TerminalSession?) = Unit
            override fun onTerminalCursorStateChange(enabled: Boolean) = Unit
            override fun getTerminalCursorStyle(): Int? = null
            override fun logError(tag: String?, message: String?) = Unit
            override fun logWarn(tag: String?, message: String?) = Unit
            override fun logInfo(tag: String?, message: String?) = Unit
            override fun logDebug(tag: String?, message: String?) = Unit
            override fun logVerbose(tag: String?, message: String?) = Unit
            override fun logStackTraceWithMessage(tag: String?, message: String?, e: Exception?) = Unit
            override fun logStackTrace(tag: String?, message: Exception?) = Unit
        }
    }
}
